name: Update renovate PRs

on:
  push:
    branches:
      - 'renovate/**'

jobs:
  check-metadata:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4
        with:
          python-version: 3.7

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: ^1

      - name: Setup helm-docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest

      - name: Run pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # renovate: tag=v3.0.0
        continue-on-error: true

      - name: Setup Gitsign
        uses: chainguard-dev/actions/setup-gitsign@main

      - name: Commit pre-commit changes
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4
        with:
          commit_message: Apply pre-commit changes
          commit_options: '-s'
